name: Run MATLAB Script

on:
  workflow_dispatch:   # Allows you to run manually

jobs:
  run-matlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run MATLAB script
        uses: matlab-actions/run-command@v2
        with:
          command: addpath('bpnet'); run('Generate_Subsets.m');